spring.application.name=backend

# MySQL Database Configuration with Environment Variable support
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/inventory_management_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# Hibernate JPA Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Security & JWT Configuration
jwt.secret=${JWT_SECRET:OEuHX/vB4qbWs48wbhWYF2vSOWZ3pmS+Xhp/1MOiiIc9XKCSLcxEDWiK8G9a3Byuckc9NVp2fdOqdaLdoc+lJQ==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Application Custom Properties
inventory.low-stock-threshold=${LOW_STOCK_THRESHOLD:5}

server.port=${PORT:8080}